# Generated by Django 4.2.27 on 2026-01-20 05:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAffidavit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_plaintiff', models.BooleanField(default=True)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('gross_wages', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rental_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('business_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_federal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_state', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_fica', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health_insurance_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health_insurance_children', models.DecimalField(decimal_places=2, default=0, help_text='Portion for children only - critical for Child Support calc', max_digits=10)),
                ('rent_mortgage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utilities', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_household', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daycare_work_related', models.DecimalField(decimal_places=2, default=0, help_text='Used in CS Worksheet', max_digits=10)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matter')),
            ],
        ),
        migrations.CreateModel(
            name='ChildSupportWorksheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mother_gross_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('father_gross_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mother_overnights', models.IntegerField(default=182)),
                ('father_overnights', models.IntegerField(default=183)),
                ('basic_obligation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_obligation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_transfer_amount', models.DecimalField(decimal_places=2, help_text='Who pays whom', max_digits=10)),
                ('paying_parent', models.CharField(max_length=10)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matter')),
            ],
        ),
    ]
