# Generated by Django 4.2.27 on 2026-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicObligationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_gross_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('one_child', models.DecimalField(decimal_places=2, max_digits=10)),
                ('two_children', models.DecimalField(decimal_places=2, max_digits=10)),
                ('three_children', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='childsupportworksheet',
            name='final_transfer_amount',
        ),
        migrations.RemoveField(
            model_name='childsupportworksheet',
            name='paying_parent',
        ),
    ]
