# Generated by Django 4.2.27 on 2026-01-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
