# Generated by Django 6.0.4 on 2026-04-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_matter_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='defendant_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
